CREATE TABLE IF NOT EXISTS movies(
id SERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL,
release_date INT NOT NULL,
director_id INT NOT NULL
);

CREATE TABLE IF NOT EXISTS directors(
id SERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL
);

